export const COMPLETED = require('./COMPLETED.png')
export const IN_PROGRESS = require('./IN_PROGRESS.png')
export const NOT_STARTED = require('./NOT_STARTED.png')
export const JUST_STARTED = require('./JUST_STARTED.png')
export const ALMOST_COMPLETED = require('./ALMOST_COMPLETED.png')
export const POSTPONED = require('./POSTPONED.png')
